exceptions middleware try 1
FreeeedomDive/MusicCollection pull request #5
Opened 2023-02-11 13:52 UTC by oveeernight

2023-02-11 14:04 UTC, FreeeedomDive requested changes

2023-02-11 14:04 UTC, FreeeedomDive commented on Backend/MusicCollection/ApiUtils/Middlewares/ExceptionsMiddleware.cs
> +            context.Response.StatusCode = e.StatusCode;
На будущее - если апишка внутренняя (между микросервисами), можно сделать еще запись самого экзепшена в респонс в json
Пример - [такая же мидлварка в телеграм-боте для стримингов](https://github.com/FreeeedomDive/MusicStreamingConverter/blob/main/MusicSearch.Api/Middlewares/ServiceExceptionHandlingMiddleware.cs)
Ну и да, для дальнейшего разбора полетов лучше снова бросить эти исключения (тоже как в примере выше)

2023-02-11 14:04 UTC, FreeeedomDive commented on Backend/MusicCollection/MusicCollection.Api/Startup.cs
> +        app.UseMiddleware<ExceptionsMiddleware>();
Эта мидлварка должна быть после логирующей, как я писал в задаче
А сейчас получается так - RequestLoggingMiddleware ловит исключение, пишет его в телеметрию, и все - эта мидлварка его уже не поймает, и юзер получит 200
И как я писал выше, ExceptionsMiddleware должна снова бросить исключение, чтобы его (для логов) уже поймала RequestLoggingMiddleware

2023-02-12 17:51 UTC, oveeernight commented on Backend/MusicCollection/MusicCollection.Api/Startup.cs
> +        app.UseMiddleware<ExceptionsMiddleware>();
fixed

2023-02-12 18:00 UTC, oveeernight commented on Backend/MusicCollection/ApiUtils/Middlewares/ExceptionsMiddleware.cs
> +            context.Response.StatusCode = e.StatusCode;
fixed

2023-02-12 18:03 UTC, FreeeedomDive approved these changes

2023-02-12 18:03 UTC, merged